import { LocalNotifications } from '@capacitor/local-notifications';
import { Share } from '@capacitor/share';
import './style.css';

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const safe = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read = (key, fallback=[]) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
let tab='בית', view='home', activeMeeting=null, toastTimer=null;
let meetings=read('isrameet.meetings'), messages=read('isrameet.messages'), user=read('isrameet.user',{name:'אורח'});
const icon = (name) => ({home:'⌂',meetings:'▣',calendar:'▦',messages:'▤',profile:'◉',video:'▰',bell:'♧',back:'‹',plus:'+',clock:'◷',users:'♧',settings:'⚙',mic:'♩',camera:'▣',screen:'▤',chat:'☷',more:'•••'})[name]||'•';
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function makeId(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function dateText(v){try{return new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function future(m){return new Date(m.when).getTime()>Date.now()}
function header(title, back=true){return `<header class="topbar">${back?'<button class="icon-btn" data-action="back" aria-label="חזרה">‹</button>':'<div class="brand-mark">IM</div>'}<div class="header-title"><b>${title}</b><small>פגישות בלי גבולות</small></div><button class="icon-btn" data-action="notifications" aria-label="התראות">♧</button></header>`}
function nav(){const items=[['בית','⌂'],['פגישות','▣'],['יומן','▦'],['הודעות','▤'],['פרופיל','◉']];return `<nav class="underbar">${items.map(([t,i])=>`<button class="nav-item ${tab===t?'selected':''}" data-tab="${t}"><span>${i}</span><small>${t}</small>${t==='הודעות'&&messages.length?'<i class="dot"></i>':''}</button>`).join('')}</nav>`}
function meetingCard(m){return `<article class="meeting-card"><div class="meeting-symbol">▰</div><div class="meeting-info"><b>${safe(m.title)}</b><small>${m.when?dateText(m.when):'מוכן להצטרפות'} · קוד ${safe(m.code)}</small><span class="status ${m.when&&future(m)?'scheduled':''}">${m.when&&future(m)?'מתוזמנת':'חדר פגישה'}</span></div><button class="round-action" data-open="${m.id}">←</button></article>`}
function home(){return `${header('בוקר טוב 👋',false)}<main class="page home-page"><section class="hero"><div class="hero-glow"></div><div class="eyebrow"><span class="live-dot"></span> המרחב שלך, בכל מקום</div><h1>רעיונות גדולים מתחילים<br>בשיחה אחת טובה.</h1><p>חדר אחד. כולם מחוברים.</p><div class="hero-actions"><button class="primary" data-action="new">＋ פגישה חדשה</button><button class="secondary" data-action="join">הצטרפות לפגישה <span>↗</span></button></div><div class="hero-orbit"><div class="orbit-ring"></div><div class="orbit-video">▰</div><span class="orb o1">✦</span><span class="orb o2">◉</span><span class="orb o3">•••</span></div></section><section class="section-head"><div><h2>הפגישות שלך</h2><p>המקום שבו דברים קורים</p></div><button class="text-btn" data-tab="פגישות">הצגת הכול ←</button></section>${meetings.length?meetings.slice(0,3).map(meetingCard).join(''):'<div class="empty-card"><div class="empty-icon">▣</div><b>עדיין אין פגישות</b><p>צור את הפגישה הראשונה שלך והזמן את כולם.</p><button class="outline" data-action="new">יצירת פגישה</button></div>'}<section class="feature-grid"><button class="feature" data-action="schedule"><span class="feature-icon purple">◷</span><b>תזמון פגישה</b><small>קובעים זמן מראש</small><span class="feature-arrow">↗</span></button><button class="feature" data-tab="יומן"><span class="feature-icon blue">▦</span><b>היומן שלי</b><small>כל התוכניות במקום אחד</small><span class="feature-arrow">↗</span></button></section><section class="trust-strip"><span>✦</span><div><b>נבנה לפרטיות</b><small>המרחב שלך, בשליטה שלך</small></div><span class="trust-lock">♧</span></section></main>${nav()}`}
function listPage(){return `${header('הפגישות שלך',false)}<main class="page"><div class="page-intro"><h1>כל הפגישות</h1><p>החדרים וההזמנות שלך במקום אחד.</p></div><div class="toolbar"><button class="primary" data-action="new">＋ פגישה חדשה</button><button class="outline" data-action="join">הצטרפות</button></div>${meetings.length?meetings.map(meetingCard).join(''):'<div class="empty-card"><div class="empty-icon">▣</div><b>עדיין אין פגישות</b><p>צור פגישה חדשה או הצטרף עם קוד שקיבלת.</p><button class="outline" data-action="new">יצירת פגישה</button></div>'}</main>${nav()}`}
function calendarPage(){const now=new Date();const days=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()+i);return d});return `${header('היומן שלי',false)}<main class="page"><div class="page-intro"><h1>הפגישות שלך, במרחב הפרטי שלך</h1><p>התוכניות הקרובות שלך</p></div><div class="calendar-card"><div class="calendar-month">${new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(now)}<span>▦</span></div><div class="days-row">${days.map((d,i)=>`<div class="day ${i===0?'today':''}"><small>${new Intl.DateTimeFormat('he-IL',{weekday:'short'}).format(d)}</small><b>${d.getDate()}</b><i></i></div>`).join('')}</div></div><div class="section-head"><div><h2>הפגישות הקרובות</h2><p>כל מה שקבעת מראש</p></div><button class="text-btn" data-action="schedule">＋ חדש</button></div>${meetings.filter(m=>m.when&&future(m)).sort((a,b)=>new Date(a.when)-new Date(b.when)).map(meetingCard).join('')||'<div class="empty-card"><div class="empty-icon">◷</div><b>אין פגישות מתוזמנות</b><p>תזמן פגישה ותקבל התראה כשהגיע הזמן.</p><button class="outline" data-action="schedule">תזמון פגישה</button></div>'}</main>${nav()}`}
function messagesPage(){return `${header('הודעות',false)}<main class="page"><div class="page-intro"><h1>הודעות</h1><p>כל השיחות והעדכונים שלך</p></div><div class="empty-card"><div class="empty-icon">▤</div><b>הכול שקט כאן בינתיים</b><p>הודעות של פגישות יופיעו כאן.</p><button class="outline" data-tab="פגישות">מעבר לפגישות</button></div></main>${nav()}`}
function profilePage(){return `${header('החשבון שלי',false)}<main class="page"><div class="profile-card"><div class="avatar">${safe((user.name||'א')[0])}</div><h2>${safe(user.name||'אורח')}</h2><p>המרחב האישי שלך ב־IsraMeet</p><button class="outline" data-action="edit-profile">עריכת פרופיל</button></div><div class="settings-list"><button data-action="notifications"><span class="settings-icon">♧</span><span><b>התראות</b><small>הגדרות התראות הפגישה</small></span><span>←</span></button><button data-action="language"><span class="settings-icon">文</span><span><b>שפה</b><small>עברית</small></span><span>←</span></button><button data-action="privacy"><span class="settings-icon">♧</span><span><b>פרטיות ואבטחה</b><small>המרחב שלך, בשליטה שלך</small></span><span>←</span></button><button data-action="recordings"><span class="settings-icon">▣</span><span><b>הקלטות</b><small>הקלטות שנשמרו במכשיר</small></span><span>←</span></button></div><p class="version">IsraMeet · חדר אחד. כולם מחוברים.</p></main>${nav()}`}
function formPage(type){const isJoin=type==='join', isSchedule=type==='schedule';const title=isJoin?'הצטרפות לפגישה':isSchedule?'תזמון פגישה':'פגישה חדשה';return `${header(title)}<main class="page form-page"><div class="form-illustration"><div class="form-orbit">▰</div></div><div class="page-intro centered"><h1>${isJoin?'נפגשים עכשיו':isSchedule?'מוכן לפגישה הבאה שלך?':'בואו נתחיל להיפגש'}</h1><p>${isJoin?'הזן קוד פגישה או קישור שקיבלת.':isSchedule?'בחר שם, תאריך ושעה — אנחנו נזכיר לך.':'צור חדר והזמן את כולם בשיתוף אחד.'}</p></div><form id="meeting-form" data-type="${type}">${!isJoin?'<label>שם הפגישה</label><input name="title" required maxlength="80" placeholder="למשל, תכנון פרויקט">':''}${isJoin?'<label>קוד פגישה או קישור</label><input name="code" required placeholder="הזן קוד או הדבק קישור">':''}${isSchedule?'<label>תאריך ושעה</label><input name="when" type="datetime-local" required>':''}<button class="primary full" type="submit">${isJoin?'המשך ←':isSchedule?'תזמון פגישה ◷':'יצירת פגישה וקישור ↗'}</button></form><div class="secure-note"><span>♧</span><div><b>חיבורים מאובטחים</b><small>הפגישות שלך, במרחב הפרטי שלך</small></div></div></main>`}
function roomPage(){const m=activeMeeting||{title:'פגישה',code:'------'};return `${header(m.title)}<main class="room-page"><div class="room-top"><div><span class="live-dot"></span> ${m.when&&future(m)?'פגישה מתוזמנת':'חדר פגישה'}</div><button class="code-chip" data-action="copy-code">${safe(m.code)} ⧉</button></div><div class="video-stage"><div class="video-placeholder"><div class="video-avatar">${safe((user.name||'א')[0])}</div><b>${safe(user.name||'את/ה')}</b><small>המצלמה כבויה</small></div><div class="waiting-badge"><span class="live-dot"></span> ממתינים למשתתפים</div><div class="room-watermark">IsraMeet</div></div><div class="room-tools"><button data-action="mic"><span>♩</span><small>מיקרופון</small></button><button data-action="camera"><span>▣</span><small>מצלמה</small></button><button data-action="screen"><span>▤</span><small>שיתוף מסך</small></button><button data-action="room-chat"><span>☷</span><small>צ׳אט</small></button><button data-action="participants"><span>♧</span><small>משתתפים</small></button></div><div class="room-notice">החדר וההזמנה נשמרו. שידור אודיו ווידאו אמיתי בין משתתפים דורש חיבור לספק מדיה.</div><button class="danger full" data-action="leave">יציאה מהפגישה</button></main>`}
function render(){const root=$('#app');root.innerHTML=view==='room'?roomPage():view==='new'||view==='join'||view==='schedule'?formPage(view):tab==='בית'?home():tab==='פגישות'?listPage():tab==='יומן'?calendarPage():tab==='הודעות'?messagesPage():profilePage();window.scrollTo(0,0)}
function openRoom(m){activeMeeting=m;view='room';render()}
async function scheduleNotification(m){try{const perm=await LocalNotifications.checkPermissions();if(perm.display!=='granted'){const req=await LocalNotifications.requestPermissions();if(req.display!=='granted')return;}const at=new Date(m.when);if(at<=new Date())return;await LocalNotifications.schedule({notifications:[{id:Math.abs(hash(m.id)),title:'הגיע זמן הפגישה שלך',body:m.title,smallIcon:'ic_stat_isrameet',schedule:{at},extra:{meetingId:m.id},channelId:'isrameet-meetings'}]});}catch(e){console.warn('Local notification unavailable',e)}}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return h}
async function initNotifications(){try{await LocalNotifications.createChannel({id:'isrameet-meetings',name:'התראות פגישות',description:'תזכורות לפגישות מתוזמנות',importance:5,sound:'default',visibility:1});await LocalNotifications.addListener('localNotificationActionPerformed',e=>{const id=e.notification.extra?.meetingId;const m=meetings.find(x=>x.id===id);if(m){tab='פגישות';openRoom(m)}})}catch{}}
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.tab){tab=t.dataset.tab;view='home';render();return}if(t.dataset.open){const m=meetings.find(x=>x.id===t.dataset.open);if(m)openRoom(m);return}const a=t.dataset.action;if(!a)return;switch(a){case'back':view='home';render();break;case'new':view='new';render();break;case'join':view='join';render();break;case'schedule':view='schedule';render();break;case'leave':view='home';tab='בית';render();toast('יצאת מהפגישה');break;case'copy-code':try{await navigator.clipboard.writeText(activeMeeting?.code||'');toast('קוד הפגישה הועתק')}catch{toast(activeMeeting?.code||'')}break;case'notifications':try{const p=await LocalNotifications.requestPermissions();toast(p.display==='granted'?'ההתראות הופעלו':'יש לאפשר התראות בהגדרות המכשיר')}catch{toast('התראות הפגישות יופעלו במכשיר Android')}break;case'mic':t.classList.toggle('tool-off');toast(t.classList.contains('tool-off')?'המיקרופון הושתק':'המיקרופון הופעל');break;case'camera':t.classList.toggle('tool-off');toast(t.classList.contains('tool-off')?'המצלמה כבויה':'המצלמה הופעלה');break;case'screen':toast('שיתוף מסך דורש חיבור למנוע מדיה של Android');break;case'room-chat':toast('צ׳אט הפגישה יופעל לאחר חיבור שירות הפגישות');break;case'participants':toast('רשימת משתתפים תתעדכן בחיבור לחדר חי');break;case'edit-profile':{const name=prompt('איך לקרוא לך?',user.name||'');if(name?.trim()){user.name=name.trim();save('isrameet.user',user);render()}break}case'language':toast('הממשק מוגדר לעברית');break;case'privacy':toast('הגדרות הפרטיות');break;case'recordings':toast('אין הקלטות שמורות במכשיר');break}});
document.addEventListener('submit',async e=>{if(e.target.id!=='meeting-form')return;e.preventDefault();const f=new FormData(e.target),type=e.target.dataset.type;if(type==='join'){let code=String(f.get('code')||'').trim().toUpperCase().split('/').filter(Boolean).pop();let m=meetings.find(x=>x.code===code)||{id:makeId(),title:'פגישה שהצטרפת אליה',code:code||makeId()};openRoom(m);return}const title=String(f.get('title')||'').trim();if(!title){toast('נא להזין שם לפגישה');return}const m={id:makeId(),title,code:makeId(),when:type==='schedule'?new Date(f.get('when')).toISOString():null,createdAt:new Date().toISOString()};if(type==='schedule'&&new Date(m.when)<=new Date()){toast('יש לבחור זמן עתידי');return}meetings.unshift(m);save('isrameet.meetings',meetings);if(m.when){await scheduleNotification(m);toast('הפגישה נקבעה. תופיע התראה בזמן שנקבע; לחיצה עליה תפתח את הפגישה.');tab='יומן';view='home';render()}else{try{await Share.share({title:'הזמנה לפגישת IsraMeet',text:`מוזמנים לפגישת IsraMeet: ${m.title}\nקוד פגישה: ${m.code}`})}catch{}openRoom(m)}});
initNotifications();render();